name: fnirs
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - numpy
  - scipy
  - pandas
  - mat73
  - matplotlib
  - jupyter
  - ipympl
  - statsmodels
  - tomli
  - mne
  - mne-nirs
  - mne-qt-browser
  - scikit-learn
  # - mesalib # probably already installed 
  # - pyvista # probably already installed
  # - pyvistaqt # probably already installed
  # - vtk>=9.2=*osmesa* # https://mne.tools/stable/install/advanced.html#installing-to-a-headless-linux-server
  - pyvirtualdisplay # optional
  # - xvfb # not really required 
  # - xvfbwrapper # not really required
